export const SET_STATE_HOOKS_ACTION = "SET_STATE_HOOKS_ACTION";
export const SET_LOADING_HOOKS_ACTION = "SET_LOADING_HOOKS_ACTION";
export const SET_SCROLLDIR_ACTION = "SET_SCROLLDIR_ACTION";
export const SET_OFFSETTOP_ACTION = "SET_OFFSETTOP_ACTION";
